import Link from 'next/link';import {HeroImage,ProductCard} from '@/components/Site';import {products} from '@/data/products';
export default function Home(){return <>
<section className="hero"><div className="hero-copy"><p className="eyebrow">为大学宿舍生活而设计</p><h1>把外面的喧闹挡住，<br/><i>给好梦留一方安静。</i></h1><p>一张认真做的床帘，不只是遮光挡蚊。<br/>也是休息、换衣、学习和安心独处的小天地。</p><div><Link className="btn" href="/products">看看适合我的床帘</Link><Link className="text-link" href="/about">认识挽梦 →</Link></div></div><HeroImage src="/images/products/product-01.jpg" alt="挽梦米色宿舍床帘" className="hero-photo"/><div className="hero-stamp">Hold on to<br/><b>every good dream.</b></div></section>
<section className="intro"><p className="eyebrow">WHY WANMENG</p><h2>我们曾经也住在宿舍，<br/>知道那些说不出口的小困扰。</h2><div className="pain-grid">{[['01','灯还亮着，眼睛却已经很累'],['02','换衣服时，希望有一点不被注视的空间'],['03','夏夜的蚊虫，让人反复醒来'],['04','尺寸不合适，安装也成了麻烦']].map(x=><article key={x[0]}><b>{x[0]}</b><p>{x[1]}</p></article>)}</div></section>
<section className="soft split"><HeroImage src="/images/products/product-06.jpg" alt="宿舍床帘细节"/><div><p className="eyebrow">OUR PROMISE</p><h2>不夸张，只把每个细节认真做好。</h2><p>从面料触感、遮光与通风，到挂点、拉链和日常清洗，我们都站在真实宿舍生活里思考。</p><ul className="checks"><li>不使用让人不安心的劣质面料</li><li>不做轻轻一拉就晃动的薄弱结构</li><li>不忽略每一条来自学生的反馈</li></ul><Link className="text-link" href="/materials">看看面料与产品细节 →</Link></div></section>
<section className="section"><div className="section-head"><div><p className="eyebrow">PRODUCTS</p><h2>找到与你的床位<br/>刚刚好的那一款。</h2></div><Link className="text-link" href="/products">查看全部产品 →</Link></div><div className="product-grid">{products.slice(0,3).map(p=><ProductCard key={p.slug} p={p}/>)}</div></section>
<section className="quote"><p>“挽住每一个学子的好梦。”</p><span>我们不追求把品牌说得很大，只希望产品能陪你走过每一个住校的夜晚。</span></section>
<section className="section"><div className="section-head"><div><p className="eyebrow">EASY GUIDE</p><h2>从测量到安装，<br/>把麻烦留在这里。</h2></div></div><div className="guide-grid">{[['01','1 分钟测量床位','/guide/measure'],['02','找到适合的款式','/products'],['03','第一次安装也不慌','/guide/install'],['04','清洗与日常收纳','/guide/care']].map(x=><Link href={x[2]} key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><b>阅读指南 →</b></Link>)}</div></section>
</>}
